spring:
  application:
    name: customer
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    driver-class-name: org.h2.Driver
    username: sa
    password: qwerty
  h2:
    console:
      enabled: true

custom:
  activeprofileName: prod

server:
  port: 48152

springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: false

